# Generated by Django 6.0.3 on 2026-08-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reminder_is_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='follow_up_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
