# Generated by Django 6.0.3 on 2026-08-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_interaction_follow_up_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='follow_up_date',
            field=models.DateField(default='2026-08-20'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interaction',
            name='follow_up_time',
            field=models.TimeField(default='10:00:00'),
            preserve_default=False,
        ),
    ]
